services:
  # server
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    volumes:
      - ./public:/var/www/html/public
    ports:
      - "88:88"
  # application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    volumes:
      - .:/var/www/html
    extra_hosts:
      - host.docker.internal:host-gateway